/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AgreementsLazyImport = createFileRoute('/agreements')()
const IndexLazyImport = createFileRoute('/')()
const AgreementAgreementNumberLazyImport = createFileRoute(
  '/agreement/$agreementNumber',
)()

// Create/Update Routes

const AgreementsLazyRoute = AgreementsLazyImport.update({
  path: '/agreements',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/agreements.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AgreementAgreementNumberLazyRoute =
  AgreementAgreementNumberLazyImport.update({
    path: '/agreement/$agreementNumber',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/agreement.$agreementNumber.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/agreements': {
      preLoaderRoute: typeof AgreementsLazyImport
      parentRoute: typeof rootRoute
    }
    '/agreement/$agreementNumber': {
      preLoaderRoute: typeof AgreementAgreementNumberLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AgreementsLazyRoute,
  AgreementAgreementNumberLazyRoute,
])

/* prettier-ignore-end */
